// <auto-generated />
using System;
using Fiap.Monitoramento.Ambiental.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Monitoramento.Ambiental.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Monitoramento.Ambiental.Models.DesastresNaturaisModel", b =>
                {
                    b.Property<int>("DesastreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesastreId"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Resolvido")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoDesastre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Tipo_Desastre");

                    b.HasKey("DesastreId");

                    b.ToTable("TBL_Desastres_Naturais", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
