name: 03 - Actions

on: 
    push:
        branches: "feature/**"

jobs:
    checkout_dotnet:
        runs-on: ubuntu-latest
        steps:            
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: .Net Core SDK
              uses: actions/setup-dotnet@v4.0.1
              with:
                dotnet-version: '8.0.x'
            - run: dotnet build

            - name: Executar scripts
              run: |
                git branch
                dotnet --version 
                dotnet clean