name: CI/CD Pipeline

on:
  push:
    branches:
    - main
    - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to environment
        run: |
          docker-compose -f docker-compose.yml up -d
        
        env:
          ENVIRONMENT: $({ github.ref == 'refs/heads/main' && 'production' || 'staging'})