name: CI/CD Pipeline

on:
  push:
    branches:
    - main
    - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
      
      - name: Install dependencies
        run: dotnet restore
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: $${{ secrets.DOCKERHUB_TOKEN }}
      
      - name : Build
        uses: docker/build-push-action@v6
        with:
          push: true