name: CI/CD Pipeline

on:
  push:
    branches:
    - main
    - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

      - name: Deploy to environment
        run: |
          docker-compose -f docker-compose.yml up -d
        
        env:
          ENVIRONMENT: $({ github.ref == 'refs/heads/main' && 'production' || 'staging'})